### PR TITLE
Splunk adaptive response notable events module

### PR DESCRIPTION
**Pull request by pranav-bhatt**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1567

This module introduces the action plugins to manage notable event adaptive response actions

### CODE REVIEW

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by justjais** [comment]
Closing the PR and moving the content of this PR to https://github.com/ansible-collections/splunk.es/pull/45

**Pull request closed without merging**
